language: r
r: release
sudo: false
cache: packages

warnings_are_errors: TRUE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

addons:
  apt:
    packages:
      - jags

env:
  global:
    - CXX_OLEVEL=2 CXX=g++
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - NOT_CRAN=true

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++" >> ~/.R/Makevars
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function" >> ~/.R/Makevars
  - echo "CXX14FLAGS+=-flto -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations" >> ~/.R/Makevars

# after_success:
#   - Rscript -e 'covr::codecov()'
