language: r
r: release
sudo: false
cache: packages

warnings_are_errors: TRUE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

addons:
  apt:
    packages:
      - jags

env:
  global:
    - CXX_OLEVEL=2 CXX=clang++
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - NOT_CRAN=true

before_install:
  - mkdir -p ~/.R/
  - echo "CXX = `R CMD config CXX`" >> ~/.R/Makevars
  - echo "CXXFLAGS = `R CMD config CXXFLAGS` -pedantic -g0" >> ~/.R/Makevars
  - echo "CXX14 = `R CMD config CXX`" >> ~/.R/Makevars
  - echo "CXX14FLAGS = `R CMD config CXXFLAGS` -pedantic -g0" >> ~/.R/Makevars
  - export CLANG_EXTRA_ARG=""
  - if [[ $CXX = "clang++" ]] ;  then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
  - sed -i.bak "s/ g++/ ${CXX}${CLANG_EXTRA_ARG}/" ~/.R/Makevars
  - sed -i.bak "s/O[0-3]/O$CXX_OLEVEL/" ~/.R/Makevars

# after_success:
#   - Rscript -e 'covr::codecov()'
